- name: Copy certificate key.
  ansible.builtin.copy:
    src: '{{ domain }}.key'
    dest: /etc/ssl/private/

- name: Copy certificate.
  ansible.builtin.copy:
    src: '{{ domain }}.crt'
    dest: /etc/ssl/certs/

- name: Create www/domain directory for html.
  ansible.builtin.file:
    path: /var/www/{{ domain }}
    state: directory
    mode: 0775 # rwx-rwx-r.x
    owner: root
    group: root

- name: Clone EVT website repo inside of www/domain directory.
  ansible.builtin.git:
    repo: https://bitbucket.org/bjgiller/evt-tech-challenge.git
    dest: /var/www/{{ domain }}

- name: Delete default nginx site.
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy nginx site.conf.
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}
    owner: root
    group: root
    mode: 0644 # rw.-r..-r..

- name: Restart nginx.
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true # sudo  
